version: '3'

services:
  next-app:
    container_name: restore-image
    build:
      context: ./
      dockerfile: Dockerfile

    # Set environment variables directly in the docker-compose file
    # Set envrionment variables based on the .env file
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network
    environment:
      - NODE_ENV=production

networks:
  my_network:
    external: true